!This script is part of vaspkit 0.73
PROGRAM PRETREAT
	IMPLICIT NONE
	INTEGER :: I,J
	DIMENSION REALVECTOR(3,3),RECIPVECTOR(3,3),LATTLEN(3)
	DOUBLE PRECISION REALVECTOR,RECIPVECTOR ,LATTLEN ,SCALING ,ALPHA, BETA,GAMMA,VOLUME
	DOUBLE PRECISION PI
	PARAMETER(PI=3.1415926)
	CHARACTER*100 SYSTEMLABEL
	OPEN(UNIT=11,FILE='CONTCAR',STATUS='OLD')
	READ(11,'(A30)')SystemLabel
	READ(UNIT=11,FMT=*) SCALING
	READ(UNIT=11,FMT=*) ((REALVECTOR(I,J),J=1,3),I=1,3)
	DO I=1,3
		CALL GETMOD(REALVECTOR(I,:),LATTLEN(I))  
	END DO
	LATTLEN=LATTLEN*SCALING
	!WRITE(*,*) LATTLEN
	
	! CALCULATE THE ANGLE BETWEEN TWO THE LATTICE
	ALPHA=ACOS(DOT_PRODUCT(REALVECTOR(2,:),REALVECTOR(3,:))*SCALING**2/&
	(LATTLEN(2)*LATTLEN(3)))*180/PI
	BETA=ACOS(DOT_PRODUCT(REALVECTOR(1,:),REALVECTOR(3,:))*SCALING**2/&
	(LATTLEN(1)*LATTLEN(3)))*180/PI
	GAMMA=ACOS(DOT_PRODUCT(REALVECTOR(1,:),REALVECTOR(2,:))*SCALING**2/&
	(LATTLEN(1)*LATTLEN(2)))*180/PI
	CALL CROSS(REALVECTOR(2,:)*SCALING,REALVECTOR(3,:)*SCALING,RECIPVECTOR(1,:))
	CALL CROSS(REALVECTOR(3,:)*SCALING,REALVECTOR(1,:)*SCALING,RECIPVECTOR(2,:))
	CALL CROSS(REALVECTOR(1,:)*SCALING,REALVECTOR(2,:)*SCALING,RECIPVECTOR(3,:))
	VOLUME=REALVECTOR(1,1)*(REALVECTOR(2,2)*REALVECTOR(3,3)-REALVECTOR(2,3)*REALVECTOR(3,2))&
		+REALVECTOR(1,2)*(REALVECTOR(2,3)*REALVECTOR(3,1)-REALVECTOR(2,1)*REALVECTOR(3,3))&
		+REALVECTOR(1,3)*(REALVECTOR(2,1)*REALVECTOR(3,2)-REALVECTOR(2,2)*REALVECTOR(3,1))
	VOLUME=VOLUME*SCALING**3
	RECIPVECTOR(:,:)=(1/VOLUME)*RECIPVECTOR(:,:) 
	OPEN(UNIT=12,FILE='vmdrc.txt',STATUS='REPLACE')    
	WRITE(12,'(A10,6F8.3,A2)') 'pbc set { ',(LATTLEN(I),I=1,3),ALPHA,BETA,GAMMA,' }'
	WRITE(12,'(A)') "pbc box -on"
	WRITE(12,'(A)') "color Display Background white"
    close(12)
	
END PROGRAM

SUBROUTINE CROSS(X,Y,Z)
	IMPLICIT NONE
	REAL(8), INTENT(IN) :: X(3)
	REAL(8), INTENT(IN) :: Y(3)
	REAL(8), INTENT(OUT) :: Z(3)
	Z(1)=X(2)*Y(3)-X(3)*Y(2)
	Z(2)=X(3)*Y(1)-X(1)*Y(3)
	Z(3)=X(1)*Y(2)-X(2)*Y(1)
	RETURN
END SUBROUTINE

SUBROUTINE GETMOD(A,GETMODEL)
	IMPLICIT NONE
	REAL(KIND=8)::A(3),GETMODEL
	GETMODEL=SQRT(A(1)**2+A(2)**2+A(3)**2)
	RETURN
END SUBROUTINE

SUBROUTINE TRAPZ(A,B,STEP,AREA)
	IMPLICIT NONE
	REAL(8),INTENT(IN) :: A, B, STEP
	REAL(8),INTENT(OUT) :: AREA
	AREA=(A+B)*STEP/2
	RETURN 
END SUBROUTINE
