#!/bin/bash
#SBATCH -J bader_NEB
#SBATCH -p DIV
#SBATCH --ntasks 24
#SBATCH --cpus-per-task 1
#SBATCH --time=72:00:00
#SBATCH --nodes 1

ulimit -s unlimited

module load intel
module load vasp
 
mpirun -np $SLURM_NTASKS vasp_std

exit
